version: '3'
services: 
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - //nodehrm:/app
      - /app/node_modules

# volumes:
#   nodemodules:
#     external: true