version: '3'
services: 
  web:
    build: 
      context: .
      dockerfile: Dockerfile

    # its hot reload - mirroring current dir into docker container  
    volumes: 
      - .\:/app

# volumes:
#   nodemodules:
#     external: true