version: '3'
services:
  web: 
    container_name: "web_service"
    build: ./web-service
    env_file: .env
    ports:
      - '${WEB_PORT}:${WEB_PORT}'
    depends_on:
      - "${MYSQL_HOST}"
    
  db:
    container_name: "database-service"
    build: ./database-service
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    volumes:
      - ./mysql_data:/var/lib/mysql

      

